name: "Security Scan Check"
description: "Fetches security vulnerabilities from GitHub API and returns counts by severity."
author: "Your GitHub Username or Organization"
branding:
  icon: "shield"
  color: "red"
inputs:
  github_token:
    description: "GitHub Token for authentication"
    required: true
outputs:
  critical_count:
    description: "Number of critical severity vulnerabilities"
  high_count:
    description: "Number of high severity vulnerabilities"
  medium_count:
    description: "Number of medium severity vulnerabilities"
  low_count:
    description: "Number of low severity vulnerabilities"
  high_critical_alerts_json:
    description: "Path to JSON file containing high and critical alerts"
runs:
  using: "composite"
  steps:
    - name: Fetch Security Vulnerabilities
      shell: bash
      run: |
        echo "Fetching Security Vulnerabilities..."
        
        response=$(curl -s -H "Authorization: token ${{ inputs.github_token }}" \
        "https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?state=open")

        # Initialize counts
        critical_count=$(echo "$response" | jq '[.[] | select(.rule.security_severity_level == "critical")] | length')
        high_count=$(echo "$response" | jq '[.[] | select(.rule.security_severity_level == "high")] | length')
        medium_count=$(echo "$response" | jq '[.[] | select(.rule.security_severity_level == "medium")] | length')
        low_count=$(echo "$response" | jq '[.[] | select(.rule.security_severity_level == "low")] | length')

        # Extract high/critical severity alerts into JSON file
        high_critical_alerts=$(echo "$response" | jq '[.[] | select(.rule.security_severity_level == "high" or .rule.security_severity_level == "critical")]')
        echo "$high_critical_alerts" > high_critical_alerts.json

        echo "critical_count=$critical_count" >> $GITHUB_OUTPUT
        echo "high_count=$high_count" >> $GITHUB_OUTPUT
        echo "medium_count=$medium_count" >> $GITHUB_OUTPUT
        echo "low_count=$low_count" >> $GITHUB_OUTPUT
        echo "high_critical_alerts_json=high_critical_alerts.json" >> $GITHUB_OUTPUT
