### **3️⃣ Create a GitHub Actions Test Workflow (`.github/workflows/test.yml`)**

name: Test GitHub Action
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
        security-events: read  # Grants permission to read security alerts


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Code Scan Check
        id: scan
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display Scan Results
        run: |
          echo "Critical Count: ${{ steps.scan.outputs.critical_count }}"
          echo "High Count: ${{ steps.scan.outputs.high_count }}"
          echo "Medium Count: ${{ steps.scan.outputs.medium_count }}"
          echo "Low Count: ${{ steps.scan.outputs.low_count }}"
          echo "High-Critical Alerts JSON Path: ${{ steps.scan.outputs.high_critical_alerts_json }}"

